import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export async function getServerSideProps(ctx) {
  let search = ctx.query.search;
  if (ctx.query.search) {
    search = ctx.query.search;
  } else {
    search = 'haikyuu';
  }
  const api = await fetch(
    'https://webraku.xyz/api/anime/kusonime?search=' +
      search +
      '&apikey=FIUkfHBi'
  );
  const data = await api.json();
  return {
    props: {
      fApi: data,
    },
  };
}

export default function Home({ fApi }) {
  const res = fApi;
  const anime = res.result;
  const animelink = res.result.download;

  return (
    <div className="container">
      <Head>
        <title>Animers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Animers</h1>

        <form>
          <input
            type="text"
            name="search"
            placeholder="Insert name of Anime and then press Enter!"
            className="placeholder:text-purple-300 border-4 text-center rounded-full w-96 p-2 text-lg border-purple-600 focus:ring-pink-500 focus:ring-2 focus:outline-none"
          ></input>
        </form>

        <h2 className="text-2xl mt-3">{anime.title_jp}</h2>
        <div className="mt-1">
          <Image
            className="rounded-lg"
            src={anime.thumbs}
            width={1000}
            height={536}
            alt={anime.title}
          ></Image>
        </div>

        <ul className="mt-10 text-lg">
          <li>Title : {anime.title}</li>
          <li>Title JP : {anime.title_jp}</li>
          <li>Genre : {anime.genre}</li>
          <li>Season : {anime.season}</li>
          <li>Producer : {anime.producer}</li>
          <li>Episode Counts : {anime.total_episode}</li>
          <li>Rating : {anime.score}</li>
          <li>Released at : {anime.released_on}</li>
          <li>Description : {anime.description}</li>
        </ul>
        <h5 className="text-2xl mt-10">Download Links</h5>
        <div className="px-10">
          <ul className="mt-2">
            {animelink.map(
              (item) => (
                '',
                (
                  <li>
                    {item.download_list.map((dw) => (
                      <li key={dw.download_list}>
                        <a href={dw.download_link}>
                          Download {anime.title} {item.resolution} from{' '}
                          {dw.downloader}
                        </a>
                      </li>
                    ))}
                  </li>
                )
              )
            )}
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
